services:
  - type: web
    name: portfolio-app
    env: python
    runtime: python-3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - --log-level info app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    disk:
      name: portfolio-data
      mountPath: /opt/render/project/src
      sizeGB: 1
